// TODO: 
const getUsers = async(req,res)=>{
    try {
        const users = await 
    } catch (error) {
        
    }
}